run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - ineffassign
    - unused
    - gofmt
    - goimports

linters-settings:
  revive:
    rules:
      - name: exported
      - name: error-return
      - name: error-naming
      - name: unused-parameter
        disabled: true
